# Generated by Django 3.1 on 2021-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aereolinea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelofactura',
            name='cajero',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
